/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const TemplatesIndexLazyImport = createFileRoute('/templates/')()
const PagesIndexLazyImport = createFileRoute('/pages/')()
const TemplatesTemplateIDIndexLazyImport = createFileRoute(
  '/templates/$templateID/',
)()
const PagesPageIDIndexLazyImport = createFileRoute('/pages/$pageID/')()
const TemplatesTemplateIDPreviewLazyImport = createFileRoute(
  '/templates/$templateID/preview',
)()
const PagesPageIDEditLazyImport = createFileRoute('/pages/$pageID/edit')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TemplatesIndexLazyRoute = TemplatesIndexLazyImport.update({
  path: '/templates/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/templates/index.lazy').then((d) => d.Route),
)

const PagesIndexLazyRoute = PagesIndexLazyImport.update({
  path: '/pages/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/pages/index.lazy').then((d) => d.Route))

const TemplatesTemplateIDIndexLazyRoute =
  TemplatesTemplateIDIndexLazyImport.update({
    path: '/templates/$templateID/',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/templates/$templateID/index.lazy').then((d) => d.Route),
  )

const PagesPageIDIndexLazyRoute = PagesPageIDIndexLazyImport.update({
  path: '/pages/$pageID/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/pages/$pageID/index.lazy').then((d) => d.Route),
)

const TemplatesTemplateIDPreviewLazyRoute =
  TemplatesTemplateIDPreviewLazyImport.update({
    path: '/templates/$templateID/preview',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/templates/$templateID/preview.lazy').then((d) => d.Route),
  )

const PagesPageIDEditLazyRoute = PagesPageIDEditLazyImport.update({
  path: '/pages/$pageID/edit',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/pages/$pageID/edit.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/pages/': {
      preLoaderRoute: typeof PagesIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/templates/': {
      preLoaderRoute: typeof TemplatesIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/pages/$pageID/edit': {
      preLoaderRoute: typeof PagesPageIDEditLazyImport
      parentRoute: typeof rootRoute
    }
    '/templates/$templateID/preview': {
      preLoaderRoute: typeof TemplatesTemplateIDPreviewLazyImport
      parentRoute: typeof rootRoute
    }
    '/pages/$pageID/': {
      preLoaderRoute: typeof PagesPageIDIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/templates/$templateID/': {
      preLoaderRoute: typeof TemplatesTemplateIDIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  PagesIndexLazyRoute,
  TemplatesIndexLazyRoute,
  PagesPageIDEditLazyRoute,
  TemplatesTemplateIDPreviewLazyRoute,
  PagesPageIDIndexLazyRoute,
  TemplatesTemplateIDIndexLazyRoute,
])

/* prettier-ignore-end */
